---
name: Provision-Test

'on':
  push:

jobs:
  build:
    if: ${{ !(contains(github.ref, 'tags/')) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          args: build --snapshot

  release:
    if: ${{ contains(github.ref, 'tags/') }}
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v6
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          args: release --skip publish
          workdir: ${{ github.workspace }}

      - uses: NuGet/setup-nuget@v2.0.1

      - run: >
          dotnet nuget push **/*.nupkg
          --api-key '${{ secrets.CHOCO_API_KEY }}'
          --source '${{ vars.CHOCO_URL }}'
          --skip-duplicate
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ./dist/dcjulian29.*_*.*
          omitBody: true
          omitName: true
          token: ${{ secrets.GITHUB_TOKEN }}
